### ISSUE TITLE
Fixing checkboxes 

### ISSUE THREAD

**Issue by kidex** [kidex/hailajob#2]
When I click on the checkboxes I can't change anything

**Comment by kidex** [comment]
30m

**Comment by costin9** [comment]
Care e diferenta dintre asta si cel caruia i-am dat deja close ?

**Comment by kidex** [comment]
aici erau checkbox-urile care nu mergeau , si acum merg

**Comment by costin9** [comment]
corect. l-am confundat cu cel de modificare a layout-ului. e in regula
