### ISSUE TITLE
Checkboxes for candi profile

### ISSUE THREAD

**Issue by costin9** [kidex/hailajob#22]
iph6 checkboxes raman pe loc si scrisul se duce in jos

**Comment by kidex** [comment]
30m

**Comment by costin9** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-502e2144de3e708288426294af8a9338311b49dbb3213b2f9b97ed8e41915656.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-64615632d1e97a26f3de5c0e9cbc79b077e81ab8f1c51f64d7957b32b14a9c4e.png)

Nu imi dau seama de modificare, in afara de faptul ca functioneaza checkboxes si au un font mai mic

**Comment by kidex** [comment]
la asta era problema ca ramaneau checkbox-urile si textul se deplasa in jos + ca nu mergeau

**Comment by costin9** [comment]
link-urile catre ”termeni si conditii” si ”legislatie” functionau, singura problema detectata de mine fiind faptul ca nu puteam sa dau check sau uncheck la fiecare. Verifica si tu daca am dreptate si pune asta in q&a apoi

**Comment by kidex** [comment]
la o anumita pagina nu mergeau , ti-am spus eu de ele , poti sa vezi exact modificarile pe care le-am facut pe github dupa numele task-ului si vezi exact ce am scris in plus sau ce am scos
