### ISSUE TITLE
Fixing functionality for adding Activity cities

### ISSUE THREAD

**Issue by kidex** [kidex/hailajob#3]
I can't hit the + button and add undefined

**Comment by kidex** [comment]
2h

**Comment by kidex** [comment]
2h

**Comment by costin9** [comment]
??? butonul de adaugat orase de activitare pentru companie functioneaza deja pe site ![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-806d599a047e163417f1f64785c37bda08520e4d1a7a765dd2d0f630b15ef17a.png)
